### ISSUE TITLE
Audio tag inside the p element not rendering

### ISSUE THREAD

**Issue by mrifni** [readium/r2-navigator-kotlin#193]
So this sample tag doesnt render but renders an empty white space in the latest test app build.

```
<p class="calibre1"><b class="calibre2">ʺAnd donʹt pursue (say) that of which you have no knowledge (of).ʺ </b>[Sooratul-Israa, 17:36]<p><audio src="https://cdn.islamic.network/quran/audio/128/ar.alafasy/2065.mp3" controls="controls">Audio not supported!</audio></p></p>

```

<img width="367" alt="Screenshot 2021-02-16 at 09 44 19" src="https://user-images.githubusercontent.com/1643992/108045702-b101d200-703b-11eb-9551-cf55af12ae4c.png">

I have sent the sample EPUB via slack.

**Comment by mickael-menu** [comment]
Note to self: shared EPUB is named `0fdf1bffb52048bd849afa7cf698c4c1_sample.epub`

**Comment by JayPanoz** [comment]
@mickael-menu see https://github.com/readium/readium-css/issues/100

**Comment by mickael-menu** [comment]
> @mickael-menu see [readium/readium-css#100](https://github.com/readium/readium-css/issues/100)

Thanks, that may be related. The `audio` elements don't have `auto` width but this is the stylesheet:

```css
audio {
    -webkit-box-shadow:  2px 2px 4px 0px #006773;
    box-shadow: 2px 2px 4px 0px #006773;
    -moz-border-radius:25px;
    -webkit-border-radius:25px;
    border-radius:25px;
}
```
